// Generated by gencpp from file darknet_ros/bbox.msg
// DO NOT EDIT!


#ifndef DARKNET_ROS_MESSAGE_BBOX_H
#define DARKNET_ROS_MESSAGE_BBOX_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace darknet_ros
{
template <class ContainerAllocator>
struct bbox_
{
  typedef bbox_<ContainerAllocator> Type;

  bbox_()
    : Class()
    , prob(0.0)
    , xmin(0)
    , ymin(0)
    , xmax(0)
    , ymax(0)  {
    }
  bbox_(const ContainerAllocator& _alloc)
    : Class(_alloc)
    , prob(0.0)
    , xmin(0)
    , ymin(0)
    , xmax(0)
    , ymax(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _Class_type;
  _Class_type Class;

   typedef float _prob_type;
  _prob_type prob;

   typedef uint32_t _xmin_type;
  _xmin_type xmin;

   typedef uint32_t _ymin_type;
  _ymin_type ymin;

   typedef uint32_t _xmax_type;
  _xmax_type xmax;

   typedef uint32_t _ymax_type;
  _ymax_type ymax;





  typedef boost::shared_ptr< ::darknet_ros::bbox_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::darknet_ros::bbox_<ContainerAllocator> const> ConstPtr;

}; // struct bbox_

typedef ::darknet_ros::bbox_<std::allocator<void> > bbox;

typedef boost::shared_ptr< ::darknet_ros::bbox > bboxPtr;
typedef boost::shared_ptr< ::darknet_ros::bbox const> bboxConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::darknet_ros::bbox_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::darknet_ros::bbox_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace darknet_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'darknet_ros': ['/home/nvidia/ros_catkin_ws/src/darknet_ros/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::darknet_ros::bbox_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::darknet_ros::bbox_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::darknet_ros::bbox_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::darknet_ros::bbox_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::darknet_ros::bbox_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::darknet_ros::bbox_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::darknet_ros::bbox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "00e2c31f0d52d092f799864f91687833";
  }

  static const char* value(const ::darknet_ros::bbox_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x00e2c31f0d52d092ULL;
  static const uint64_t static_value2 = 0xf799864f91687833ULL;
};

template<class ContainerAllocator>
struct DataType< ::darknet_ros::bbox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "darknet_ros/bbox";
  }

  static const char* value(const ::darknet_ros::bbox_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::darknet_ros::bbox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string Class\n\
float32 prob\n\
uint32 xmin\n\
uint32 ymin\n\
uint32 xmax\n\
uint32 ymax\n\
";
  }

  static const char* value(const ::darknet_ros::bbox_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::darknet_ros::bbox_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.Class);
      stream.next(m.prob);
      stream.next(m.xmin);
      stream.next(m.ymin);
      stream.next(m.xmax);
      stream.next(m.ymax);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct bbox_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::darknet_ros::bbox_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::darknet_ros::bbox_<ContainerAllocator>& v)
  {
    s << indent << "Class: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.Class);
    s << indent << "prob: ";
    Printer<float>::stream(s, indent + "  ", v.prob);
    s << indent << "xmin: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.xmin);
    s << indent << "ymin: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.ymin);
    s << indent << "xmax: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.xmax);
    s << indent << "ymax: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.ymax);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DARKNET_ROS_MESSAGE_BBOX_H
